# Generated by Django 3.1.7 on 2021-03-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='executed',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
